yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "vue-loader@*":
    dependencies:
      "webpack": "5.38.1"
  "sass-loader@*":
    dependencies:
      "sass": "^1.3.0"
  "@material/segmented-button@*":
    dependencies:
      "tslib": "*"
